POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlaSIsImlkIjoiNjU5ZDk1YmNkY2QyZWY3NDZlNDdjMTgxIiwiaWF0IjoxNzA0ODM0MDYxfQ.kS4z1mIpzNV7BlAZEnZOezCcAzvuANnyUYLI_VrDzrE

{
  "title": "Msjodss",
  "author": "Sanni",
  "url": "heihei.fi",
  "likes": 10
}